version: '3.7'
services:
  docker:
    image: postgres:13-alpine3.19
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_DB=docker
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=qwerty1234