version: '3.7'
services:
  db:
    image: postgres:13-alpine3.19
    ports:
      - '9999:9999'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=qwerty1234